# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: ''
Darwin: ''
Linux: '/home/bull/Shotgun_Storage/sg_ep_tools'

# End of file.
